version: '3.9'

services:
  postgres:
    container_name: postgresdb
    image: postgres:15
    restart: unless-stopped
    ports:
      - "5431:5432"
    volumes:
      - '$DB_HOME/postgresql:/var/lib/postgresql/data'
    shm_size: 128mb
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD





